package InterfazSistema;

import Codigo.LogicaAperturaCuenta;
import java.awt.Color;

/**
 *
 * @author axels
 */
public class AperturaCuenta extends javax.swing.JFrame {

    /**
     * Creates new form AperturaCuenta
     */
    public AperturaCuenta() {
        initComponents();
        this.setLocationRelativeTo(null);
        labelNoCuenta.setVisible(false);
        labelCodigoCliente.setVisible(false);
        labelNombreAC.setVisible(false);
        labelApellidosAC.setVisible(false);
        labelFechaAperturaCuenta.setVisible(false);
        tituloNoCuenta.setVisible(false);
        tituloCodigoCliente.setVisible(false);
        tituloNombreAC.setVisible(false);
        tituloApellidosAC.setVisible(false);
        tituloFechaAperturaCuenta.setVisible(false);
        advertenciaCampoRC1.setVisible(false);
        advertenciaCampoRC2.setVisible(false);
        advertenciaCampoRC3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipoCuenta = new javax.swing.ButtonGroup();
        fondoPanelAperturaCuenta = new javax.swing.JPanel();
        tituloAperturaCuenta = new javax.swing.JLabel();
        tituloFechaAperturaCuenta = new javax.swing.JLabel();
        labelFechaAperturaCuenta = new javax.swing.JLabel();
        tituloApellidosAC = new javax.swing.JLabel();
        labelApellidosAC = new javax.swing.JLabel();
        tituloNombreAC = new javax.swing.JLabel();
        labelNombreAC = new javax.swing.JLabel();
        tituloCodigoCliente = new javax.swing.JLabel();
        labelCodigoCliente = new javax.swing.JLabel();
        tituloNoCuenta = new javax.swing.JLabel();
        labelNoCuenta = new javax.swing.JLabel();
        botonAperturaCuenta = new javax.swing.JPanel();
        tituloBotonAperturaCuenta = new javax.swing.JLabel();
        advertenciaExistenciaDPI = new javax.swing.JLabel();
        advertenciaCampoRC3 = new javax.swing.JLabel();
        advertenciaCampoRC2 = new javax.swing.JLabel();
        advertenciaCampoRC1 = new javax.swing.JLabel();
        tituloDPIAperturaCuenta = new javax.swing.JLabel();
        ingresoDPIAperturaCuenta = new javax.swing.JTextField();
        tituloTipoCuenta = new javax.swing.JLabel();
        botonAhorro = new javax.swing.JRadioButton();
        botonMonetaria = new javax.swing.JRadioButton();
        fondoBotonesTipoCuenta = new javax.swing.JLabel();
        tituloMontoInicial = new javax.swing.JLabel();
        ingresoMontoInicial = new javax.swing.JTextField();
        botonRegresoInicio1 = new javax.swing.JPanel();
        tituloRegresoInicio1 = new javax.swing.JLabel();
        cuadroAperturaCuenta = new javax.swing.JLabel();
        fondoAperturaCuenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fondoPanelAperturaCuenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloAperturaCuenta.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        tituloAperturaCuenta.setForeground(new java.awt.Color(0, 0, 0));
        tituloAperturaCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloAperturaCuenta.setText("Apertura de Cuenta");
        fondoPanelAperturaCuenta.add(tituloAperturaCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 50));

        tituloFechaAperturaCuenta.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloFechaAperturaCuenta.setForeground(new java.awt.Color(51, 51, 51));
        tituloFechaAperturaCuenta.setText("Fecha");
        fondoPanelAperturaCuenta.add(tituloFechaAperturaCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 150, -1));

        labelFechaAperturaCuenta.setBackground(new java.awt.Color(255, 255, 255));
        labelFechaAperturaCuenta.setForeground(new java.awt.Color(0, 0, 0));
        labelFechaAperturaCuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        labelFechaAperturaCuenta.setOpaque(true);
        fondoPanelAperturaCuenta.add(labelFechaAperturaCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 340, 40));

        tituloApellidosAC.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloApellidosAC.setForeground(new java.awt.Color(51, 51, 51));
        tituloApellidosAC.setText("Apellidos");
        fondoPanelAperturaCuenta.add(tituloApellidosAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 150, -1));

        labelApellidosAC.setBackground(new java.awt.Color(255, 255, 255));
        labelApellidosAC.setForeground(new java.awt.Color(0, 0, 0));
        labelApellidosAC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        labelApellidosAC.setOpaque(true);
        fondoPanelAperturaCuenta.add(labelApellidosAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 340, 40));

        tituloNombreAC.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloNombreAC.setForeground(new java.awt.Color(51, 51, 51));
        tituloNombreAC.setText("Nombre");
        fondoPanelAperturaCuenta.add(tituloNombreAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 150, -1));

        labelNombreAC.setBackground(new java.awt.Color(255, 255, 255));
        labelNombreAC.setForeground(new java.awt.Color(0, 0, 0));
        labelNombreAC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        labelNombreAC.setOpaque(true);
        fondoPanelAperturaCuenta.add(labelNombreAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 340, 40));

        tituloCodigoCliente.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloCodigoCliente.setForeground(new java.awt.Color(51, 51, 51));
        tituloCodigoCliente.setText("Código");
        fondoPanelAperturaCuenta.add(tituloCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 150, -1));

        labelCodigoCliente.setBackground(new java.awt.Color(255, 255, 255));
        labelCodigoCliente.setForeground(new java.awt.Color(0, 0, 0));
        labelCodigoCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        labelCodigoCliente.setOpaque(true);
        fondoPanelAperturaCuenta.add(labelCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 340, 40));

        tituloNoCuenta.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloNoCuenta.setForeground(new java.awt.Color(51, 51, 51));
        tituloNoCuenta.setText("No. Cuenta");
        fondoPanelAperturaCuenta.add(tituloNoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 150, -1));

        labelNoCuenta.setBackground(new java.awt.Color(255, 255, 255));
        labelNoCuenta.setForeground(new java.awt.Color(0, 0, 0));
        labelNoCuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        labelNoCuenta.setOpaque(true);
        fondoPanelAperturaCuenta.add(labelNoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 340, 40));

        botonAperturaCuenta.setBackground(new java.awt.Color(204, 204, 204));
        botonAperturaCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAperturaCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAperturaCuentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAperturaCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAperturaCuentaMouseExited(evt);
            }
        });

        tituloBotonAperturaCuenta.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloBotonAperturaCuenta.setForeground(new java.awt.Color(0, 0, 0));
        tituloBotonAperturaCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloBotonAperturaCuenta.setText("Aperturar Cuenta");

        javax.swing.GroupLayout botonAperturaCuentaLayout = new javax.swing.GroupLayout(botonAperturaCuenta);
        botonAperturaCuenta.setLayout(botonAperturaCuentaLayout);
        botonAperturaCuentaLayout.setHorizontalGroup(
            botonAperturaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloBotonAperturaCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        botonAperturaCuentaLayout.setVerticalGroup(
            botonAperturaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloBotonAperturaCuenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        fondoPanelAperturaCuenta.add(botonAperturaCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 160, 40));

        advertenciaExistenciaDPI.setFont(new java.awt.Font("Unispace", 0, 10)); // NOI18N
        advertenciaExistenciaDPI.setForeground(new java.awt.Color(153, 0, 0));
        advertenciaExistenciaDPI.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fondoPanelAperturaCuenta.add(advertenciaExistenciaDPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 340, 15));

        advertenciaCampoRC3.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        advertenciaCampoRC3.setForeground(new java.awt.Color(153, 0, 0));
        advertenciaCampoRC3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        advertenciaCampoRC3.setText("CAMPO REQUERIDO");
        fondoPanelAperturaCuenta.add(advertenciaCampoRC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 120, -1));

        advertenciaCampoRC2.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        advertenciaCampoRC2.setForeground(new java.awt.Color(153, 0, 0));
        advertenciaCampoRC2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        advertenciaCampoRC2.setText("CAMPO REQUERIDO");
        fondoPanelAperturaCuenta.add(advertenciaCampoRC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 120, -1));

        advertenciaCampoRC1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        advertenciaCampoRC1.setForeground(new java.awt.Color(153, 0, 0));
        advertenciaCampoRC1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        advertenciaCampoRC1.setText("CAMPO REQUERIDO");
        fondoPanelAperturaCuenta.add(advertenciaCampoRC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 120, -1));

        tituloDPIAperturaCuenta.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloDPIAperturaCuenta.setForeground(new java.awt.Color(51, 51, 51));
        tituloDPIAperturaCuenta.setText("DPI");
        fondoPanelAperturaCuenta.add(tituloDPIAperturaCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, -1));

        ingresoDPIAperturaCuenta.setBackground(new java.awt.Color(255, 255, 255));
        ingresoDPIAperturaCuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ingresoDPIAperturaCuenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ingresoDPIAperturaCuentaFocusLost(evt);
            }
        });
        ingresoDPIAperturaCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresoDPIAperturaCuentaKeyTyped(evt);
            }
        });
        fondoPanelAperturaCuenta.add(ingresoDPIAperturaCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 340, 40));

        tituloTipoCuenta.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloTipoCuenta.setForeground(new java.awt.Color(51, 51, 51));
        tituloTipoCuenta.setText("Tipo de Cuenta");
        fondoPanelAperturaCuenta.add(tituloTipoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 150, -1));

        botonAhorro.setBackground(new java.awt.Color(255, 255, 255));
        grupoTipoCuenta.add(botonAhorro);
        botonAhorro.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        botonAhorro.setForeground(new java.awt.Color(0, 0, 0));
        botonAhorro.setText("De Ahorro");
        botonAhorro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        fondoPanelAperturaCuenta.add(botonAhorro, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 160, 20));

        botonMonetaria.setBackground(new java.awt.Color(255, 255, 255));
        grupoTipoCuenta.add(botonMonetaria);
        botonMonetaria.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        botonMonetaria.setForeground(new java.awt.Color(0, 0, 0));
        botonMonetaria.setText("Monetaria");
        botonMonetaria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        fondoPanelAperturaCuenta.add(botonMonetaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 160, 20));

        fondoBotonesTipoCuenta.setBackground(new java.awt.Color(255, 255, 255));
        fondoBotonesTipoCuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        fondoBotonesTipoCuenta.setOpaque(true);
        fondoPanelAperturaCuenta.add(fondoBotonesTipoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 340, 40));

        tituloMontoInicial.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloMontoInicial.setForeground(new java.awt.Color(51, 51, 51));
        tituloMontoInicial.setText("Monto Inicial");
        fondoPanelAperturaCuenta.add(tituloMontoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, -1));

        ingresoMontoInicial.setBackground(new java.awt.Color(255, 255, 255));
        ingresoMontoInicial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ingresoMontoInicial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ingresoMontoInicialFocusLost(evt);
            }
        });
        ingresoMontoInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresoMontoInicialKeyTyped(evt);
            }
        });
        fondoPanelAperturaCuenta.add(ingresoMontoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 340, 40));

        botonRegresoInicio1.setBackground(new java.awt.Color(246, 245, 242));
        botonRegresoInicio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresoInicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegresoInicio1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegresoInicio1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegresoInicio1MouseExited(evt);
            }
        });

        tituloRegresoInicio1.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloRegresoInicio1.setForeground(new java.awt.Color(102, 102, 102));
        tituloRegresoInicio1.setText(" Regresar al Inicio");

        javax.swing.GroupLayout botonRegresoInicio1Layout = new javax.swing.GroupLayout(botonRegresoInicio1);
        botonRegresoInicio1.setLayout(botonRegresoInicio1Layout);
        botonRegresoInicio1Layout.setHorizontalGroup(
            botonRegresoInicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloRegresoInicio1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        botonRegresoInicio1Layout.setVerticalGroup(
            botonRegresoInicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloRegresoInicio1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        fondoPanelAperturaCuenta.add(botonRegresoInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 720, 50));

        cuadroAperturaCuenta.setBackground(new java.awt.Color(246, 245, 242));
        cuadroAperturaCuenta.setOpaque(true);
        fondoPanelAperturaCuenta.add(cuadroAperturaCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 720));

        fondoAperturaCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondos/fondos/fondoAperturaCuenta.png"))); // NOI18N
        fondoPanelAperturaCuenta.add(fondoAperturaCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanelAperturaCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanelAperturaCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresoInicio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresoInicio1MouseClicked
        Inicio regresarInicio1 = new Inicio();
        regresarInicio1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegresoInicio1MouseClicked

    private void botonRegresoInicio1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresoInicio1MouseEntered
        botonRegresoInicio1.setBackground(new Color(227,226,223));
    }//GEN-LAST:event_botonRegresoInicio1MouseEntered

    private void botonRegresoInicio1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresoInicio1MouseExited
        botonRegresoInicio1.setBackground(new Color(246,245,242));
    }//GEN-LAST:event_botonRegresoInicio1MouseExited

    private void botonAperturaCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAperturaCuentaMouseEntered
        botonAperturaCuenta.setBackground(new Color(188,188,188));
    }//GEN-LAST:event_botonAperturaCuentaMouseEntered

    private void botonAperturaCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAperturaCuentaMouseExited
        botonAperturaCuenta.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_botonAperturaCuentaMouseExited

    private void botonAperturaCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAperturaCuentaMouseClicked
        if(ingresoMontoInicial.getText().trim().isEmpty() || ingresoDPIAperturaCuenta.getText().trim().isEmpty() || (!botonAhorro.isSelected() && !botonMonetaria.isSelected())){
            if(ingresoMontoInicial.getText().trim().isEmpty()){
                advertenciaCampoRC1.setVisible(true);
            }else{
                advertenciaCampoRC1.setVisible(false);
            }
            if(!botonAhorro.isSelected() && !botonMonetaria.isSelected()){
                advertenciaCampoRC2.setVisible(true);
            }else{
                advertenciaCampoRC2.setVisible(false);
            }
            if(ingresoDPIAperturaCuenta.getText().trim().isEmpty()){
                advertenciaCampoRC3.setVisible(true);
            }else{
                advertenciaCampoRC3.setVisible(false);
            }
        }else{
            advertenciaCampoRC1.setVisible(false);
            advertenciaCampoRC2.setVisible(false);
            advertenciaCampoRC3.setVisible(false);

            String tipCuen = "";
            if(botonAhorro.isSelected()){
                tipCuen = "Ahorro";
            }else if(botonMonetaria.isSelected()){
                tipCuen = "Monetaria";
            }else{
                tipCuen = "Invalida";
            }

            double montoInicial = Double.parseDouble(ingresoMontoInicial.getText());
            String tipoCuenta = tipCuen;
            String dpi = ingresoDPIAperturaCuenta.getText();


            LogicaAperturaCuenta aperturaCuenta = new LogicaAperturaCuenta(montoInicial, tipoCuenta, dpi);
            aperturaCuenta.verNombreYApellidos();
            aperturaCuenta.abrirCuenta();
            aperturaCuenta.abrirCuentaArchivo();
            
            if(aperturaCuenta.getValidacionDPIVista().equals("verdad")){
                labelNoCuenta.setVisible(true);
                labelCodigoCliente.setVisible(true);
                labelNombreAC.setVisible(true);
                labelApellidosAC.setVisible(true);
                labelFechaAperturaCuenta.setVisible(true);
                tituloNoCuenta.setVisible(true);
                tituloCodigoCliente.setVisible(true);
                tituloNombreAC.setVisible(true);
                tituloApellidosAC.setVisible(true);
                tituloFechaAperturaCuenta.setVisible(true);
            }            
            
            if(aperturaCuenta.getValidacionDPIVista().equals("verdad")){
                labelNombreAC.setText(" " + aperturaCuenta.getNombreEncontrado());
                labelApellidosAC.setText(" " + aperturaCuenta.getApellidosEncontrado());
                labelCodigoCliente.setText(" " + aperturaCuenta.getCodigoCliente());
                labelFechaAperturaCuenta.setText(" " + aperturaCuenta.getFechaApertura());
                labelNoCuenta.setText(" " + aperturaCuenta.getNoCuenta());
            }
            advertenciaExistenciaDPI.setText(aperturaCuenta.getAvisoExistenciaDpi());
            
        }
    }//GEN-LAST:event_botonAperturaCuentaMouseClicked

    private void ingresoMontoInicialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresoMontoInicialKeyTyped
        int key = evt.getKeyChar();
        
        boolean numero = key >= 48 && key <= 57 || key == 46;
        
        if(!numero){
            evt.consume();
        }
    }//GEN-LAST:event_ingresoMontoInicialKeyTyped

    private void ingresoDPIAperturaCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresoDPIAperturaCuentaKeyTyped
        int key = evt.getKeyChar();
        
        boolean numero = key >= 48 && key <= 57;
        
        if(!numero){
            evt.consume();
        }
    }//GEN-LAST:event_ingresoDPIAperturaCuentaKeyTyped

    private void ingresoMontoInicialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoMontoInicialFocusLost
        if(ingresoMontoInicial.getText().trim().isEmpty()){
            advertenciaCampoRC1.setVisible(true);
        }else{
            advertenciaCampoRC1.setVisible(false);
        }
    }//GEN-LAST:event_ingresoMontoInicialFocusLost

    private void ingresoDPIAperturaCuentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoDPIAperturaCuentaFocusLost
        if(ingresoDPIAperturaCuenta.getText().trim().isEmpty()){
            advertenciaCampoRC3.setVisible(true);
        }else{
            advertenciaCampoRC3.setVisible(false);
        }
    }//GEN-LAST:event_ingresoDPIAperturaCuentaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AperturaCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AperturaCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AperturaCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AperturaCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AperturaCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advertenciaCampoRC1;
    private javax.swing.JLabel advertenciaCampoRC2;
    private javax.swing.JLabel advertenciaCampoRC3;
    private javax.swing.JLabel advertenciaExistenciaDPI;
    private javax.swing.JRadioButton botonAhorro;
    private javax.swing.JPanel botonAperturaCuenta;
    private javax.swing.JRadioButton botonMonetaria;
    private javax.swing.JPanel botonRegresoInicio1;
    private javax.swing.JLabel cuadroAperturaCuenta;
    private javax.swing.JLabel fondoAperturaCuenta;
    private javax.swing.JLabel fondoBotonesTipoCuenta;
    private javax.swing.JPanel fondoPanelAperturaCuenta;
    private javax.swing.ButtonGroup grupoTipoCuenta;
    private javax.swing.JTextField ingresoDPIAperturaCuenta;
    private javax.swing.JTextField ingresoMontoInicial;
    private javax.swing.JLabel labelApellidosAC;
    private javax.swing.JLabel labelCodigoCliente;
    private javax.swing.JLabel labelFechaAperturaCuenta;
    private javax.swing.JLabel labelNoCuenta;
    private javax.swing.JLabel labelNombreAC;
    private javax.swing.JLabel tituloApellidosAC;
    private javax.swing.JLabel tituloAperturaCuenta;
    private javax.swing.JLabel tituloBotonAperturaCuenta;
    private javax.swing.JLabel tituloCodigoCliente;
    private javax.swing.JLabel tituloDPIAperturaCuenta;
    private javax.swing.JLabel tituloFechaAperturaCuenta;
    private javax.swing.JLabel tituloMontoInicial;
    private javax.swing.JLabel tituloNoCuenta;
    private javax.swing.JLabel tituloNombreAC;
    private javax.swing.JLabel tituloRegresoInicio1;
    private javax.swing.JLabel tituloTipoCuenta;
    // End of variables declaration//GEN-END:variables
}
