/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazSistema;

import Codigo.LogicaDeposito_Y_Retiro;
import java.awt.Color;

/**
 *
 * @author axels
 */
public class RealizarRetiro extends javax.swing.JFrame {

    /**
     * Creates new form RealizarRetiro
     */
    public RealizarRetiro() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.advertenciaCampoR1.setVisible(false);
        this.advertenciaCampoR2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanelRealizarRetiro = new javax.swing.JPanel();
        tituloRealizarRetiro = new javax.swing.JLabel();
        botonRealizarRetiro = new javax.swing.JPanel();
        tituloBotonRealizarRetiro = new javax.swing.JLabel();
        tituloNoCuentaRetiro = new javax.swing.JLabel();
        ingresoNoCuentaRetiro = new javax.swing.JTextField();
        tituloMontoRetiro = new javax.swing.JLabel();
        advertenciaMontoInvalido = new javax.swing.JLabel();
        ingresoMontoRetiro = new javax.swing.JTextField();
        botonRegresoInicio1 = new javax.swing.JPanel();
        tituloRegresoInicio1 = new javax.swing.JLabel();
        advertenciaCampoR1 = new javax.swing.JLabel();
        advertenciaCampoR2 = new javax.swing.JLabel();
        avisoTransferencia = new javax.swing.JLabel();
        advertenciaExistenciaCuentaR = new javax.swing.JLabel();
        cuadroRealizarRetiro = new javax.swing.JLabel();
        fondoRealizarRetiro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fondoPanelRealizarRetiro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloRealizarRetiro.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        tituloRealizarRetiro.setForeground(new java.awt.Color(0, 0, 0));
        tituloRealizarRetiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloRealizarRetiro.setText("Retiro");
        fondoPanelRealizarRetiro.add(tituloRealizarRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 50));

        botonRealizarRetiro.setBackground(new java.awt.Color(204, 204, 204));
        botonRealizarRetiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRealizarRetiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRealizarRetiroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRealizarRetiroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRealizarRetiroMouseExited(evt);
            }
        });

        tituloBotonRealizarRetiro.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tituloBotonRealizarRetiro.setForeground(new java.awt.Color(0, 0, 0));
        tituloBotonRealizarRetiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloBotonRealizarRetiro.setText("Retirar");

        javax.swing.GroupLayout botonRealizarRetiroLayout = new javax.swing.GroupLayout(botonRealizarRetiro);
        botonRealizarRetiro.setLayout(botonRealizarRetiroLayout);
        botonRealizarRetiroLayout.setHorizontalGroup(
            botonRealizarRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonRealizarRetiroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tituloBotonRealizarRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        botonRealizarRetiroLayout.setVerticalGroup(
            botonRealizarRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonRealizarRetiroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tituloBotonRealizarRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fondoPanelRealizarRetiro.add(botonRealizarRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 150, 40));

        tituloNoCuentaRetiro.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloNoCuentaRetiro.setForeground(new java.awt.Color(51, 51, 51));
        tituloNoCuentaRetiro.setText("No. Cuenta");
        fondoPanelRealizarRetiro.add(tituloNoCuentaRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, -1));

        ingresoNoCuentaRetiro.setBackground(new java.awt.Color(255, 255, 255));
        ingresoNoCuentaRetiro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ingresoNoCuentaRetiro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ingresoNoCuentaRetiroFocusLost(evt);
            }
        });
        ingresoNoCuentaRetiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresoNoCuentaRetiroKeyTyped(evt);
            }
        });
        fondoPanelRealizarRetiro.add(ingresoNoCuentaRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 340, 40));

        tituloMontoRetiro.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloMontoRetiro.setForeground(new java.awt.Color(51, 51, 51));
        tituloMontoRetiro.setText("Monto");
        fondoPanelRealizarRetiro.add(tituloMontoRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, -1));

        advertenciaMontoInvalido.setFont(new java.awt.Font("Unispace", 0, 10)); // NOI18N
        advertenciaMontoInvalido.setForeground(new java.awt.Color(153, 0, 0));
        advertenciaMontoInvalido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fondoPanelRealizarRetiro.add(advertenciaMontoInvalido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 330, 15));

        ingresoMontoRetiro.setBackground(new java.awt.Color(255, 255, 255));
        ingresoMontoRetiro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ingresoMontoRetiro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ingresoMontoRetiroFocusLost(evt);
            }
        });
        ingresoMontoRetiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresoMontoRetiroKeyTyped(evt);
            }
        });
        fondoPanelRealizarRetiro.add(ingresoMontoRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 340, 40));

        botonRegresoInicio1.setBackground(new java.awt.Color(246, 245, 242));
        botonRegresoInicio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresoInicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegresoInicio1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegresoInicio1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegresoInicio1MouseExited(evt);
            }
        });

        tituloRegresoInicio1.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloRegresoInicio1.setForeground(new java.awt.Color(102, 102, 102));
        tituloRegresoInicio1.setText(" Regresar al Inicio");

        javax.swing.GroupLayout botonRegresoInicio1Layout = new javax.swing.GroupLayout(botonRegresoInicio1);
        botonRegresoInicio1.setLayout(botonRegresoInicio1Layout);
        botonRegresoInicio1Layout.setHorizontalGroup(
            botonRegresoInicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloRegresoInicio1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        botonRegresoInicio1Layout.setVerticalGroup(
            botonRegresoInicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloRegresoInicio1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        fondoPanelRealizarRetiro.add(botonRegresoInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 360, 50));

        advertenciaCampoR1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        advertenciaCampoR1.setForeground(new java.awt.Color(153, 0, 0));
        advertenciaCampoR1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        advertenciaCampoR1.setText("CAMPO REQUERIDO");
        fondoPanelRealizarRetiro.add(advertenciaCampoR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 120, -1));

        advertenciaCampoR2.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        advertenciaCampoR2.setForeground(new java.awt.Color(153, 0, 0));
        advertenciaCampoR2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        advertenciaCampoR2.setText("CAMPO REQUERIDO");
        fondoPanelRealizarRetiro.add(advertenciaCampoR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 120, -1));

        avisoTransferencia.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        avisoTransferencia.setForeground(new java.awt.Color(0, 153, 51));
        avisoTransferencia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fondoPanelRealizarRetiro.add(avisoTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 330, 15));

        advertenciaExistenciaCuentaR.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        advertenciaExistenciaCuentaR.setForeground(new java.awt.Color(153, 0, 0));
        advertenciaExistenciaCuentaR.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fondoPanelRealizarRetiro.add(advertenciaExistenciaCuentaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 330, 15));

        cuadroRealizarRetiro.setBackground(new java.awt.Color(246, 245, 242));
        cuadroRealizarRetiro.setOpaque(true);
        fondoPanelRealizarRetiro.add(cuadroRealizarRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 720));

        fondoRealizarRetiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondos/fondos/fondoRealizarRetiro.png"))); // NOI18N
        fondoPanelRealizarRetiro.add(fondoRealizarRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanelRealizarRetiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanelRealizarRetiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresoInicio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresoInicio1MouseClicked
        Inicio regresarInicio1 = new Inicio();
        regresarInicio1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegresoInicio1MouseClicked

    private void botonRegresoInicio1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresoInicio1MouseEntered
        botonRegresoInicio1.setBackground(new Color(227,226,223));
    }//GEN-LAST:event_botonRegresoInicio1MouseEntered

    private void botonRegresoInicio1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresoInicio1MouseExited
        botonRegresoInicio1.setBackground(new Color(246,245,242));
    }//GEN-LAST:event_botonRegresoInicio1MouseExited

    private void botonRealizarRetiroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRealizarRetiroMouseEntered
        botonRealizarRetiro.setBackground(new Color(188,188,188));
    }//GEN-LAST:event_botonRealizarRetiroMouseEntered

    private void botonRealizarRetiroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRealizarRetiroMouseExited
        botonRealizarRetiro.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_botonRealizarRetiroMouseExited

    private void botonRealizarRetiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRealizarRetiroMouseClicked
        this.avisoTransferencia.setText("");
        if(ingresoNoCuentaRetiro.getText().trim().isEmpty() || ingresoMontoRetiro.getText().trim().isEmpty()){
            if(ingresoNoCuentaRetiro.getText().trim().isEmpty()){
                advertenciaCampoR1.setVisible(true);
            }else{
                advertenciaCampoR1.setVisible(false);
            }
            if(ingresoMontoRetiro.getText().trim().isEmpty()){
                advertenciaCampoR2.setVisible(true);
            }else{
                advertenciaCampoR2.setVisible(false);
            }
        }else{
            String noCuenta = ingresoNoCuentaRetiro.getText();
            double monto = Double.parseDouble(ingresoMontoRetiro.getText());


            LogicaDeposito_Y_Retiro retiro = new LogicaDeposito_Y_Retiro(noCuenta, monto);

            retiro.leerDatosCuenta();
            retiro.retiro();
            this.advertenciaMontoInvalido.setText(retiro.getAvisoMonto());
            this.advertenciaExistenciaCuentaR.setText(retiro.getAvisoCuenta());
            this.avisoTransferencia.setText(retiro.getAvisoTransaccion());
            this.ingresoNoCuentaRetiro.setText("");
            this.ingresoMontoRetiro.setText("");
            this.advertenciaCampoR1.setVisible(false);
            this.advertenciaCampoR2.setVisible(false);
        }
    }//GEN-LAST:event_botonRealizarRetiroMouseClicked

    private void ingresoMontoRetiroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresoMontoRetiroKeyTyped
        int key = evt.getKeyChar();
        
        boolean numero = key >= 48 && key <= 57 || key == 46;
        
        if(!numero){
            evt.consume();
        }
    }//GEN-LAST:event_ingresoMontoRetiroKeyTyped

    private void ingresoNoCuentaRetiroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresoNoCuentaRetiroKeyTyped
        int key = evt.getKeyChar();
        
        boolean numero = key >= 48 && key <= 57;
        
        if(!numero){
            evt.consume();
        }
    }//GEN-LAST:event_ingresoNoCuentaRetiroKeyTyped

    private void ingresoNoCuentaRetiroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoNoCuentaRetiroFocusLost
        if(ingresoNoCuentaRetiro.getText().trim().isEmpty()){
            advertenciaCampoR1.setVisible(true);
        }else{
            advertenciaCampoR1.setVisible(false);
        }
    }//GEN-LAST:event_ingresoNoCuentaRetiroFocusLost

    private void ingresoMontoRetiroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoMontoRetiroFocusLost
        if(ingresoMontoRetiro.getText().trim().isEmpty()){
            advertenciaCampoR2.setVisible(true);
        }else{
            advertenciaCampoR2.setVisible(false);
        }
    }//GEN-LAST:event_ingresoMontoRetiroFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealizarRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealizarRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealizarRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealizarRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealizarRetiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advertenciaCampoR1;
    private javax.swing.JLabel advertenciaCampoR2;
    private javax.swing.JLabel advertenciaExistenciaCuentaR;
    private javax.swing.JLabel advertenciaMontoInvalido;
    private javax.swing.JLabel avisoTransferencia;
    private javax.swing.JPanel botonRealizarRetiro;
    private javax.swing.JPanel botonRegresoInicio1;
    private javax.swing.JLabel cuadroRealizarRetiro;
    private javax.swing.JPanel fondoPanelRealizarRetiro;
    private javax.swing.JLabel fondoRealizarRetiro;
    private javax.swing.JTextField ingresoMontoRetiro;
    private javax.swing.JTextField ingresoNoCuentaRetiro;
    private javax.swing.JLabel tituloBotonRealizarRetiro;
    private javax.swing.JLabel tituloMontoRetiro;
    private javax.swing.JLabel tituloNoCuentaRetiro;
    private javax.swing.JLabel tituloRealizarRetiro;
    private javax.swing.JLabel tituloRegresoInicio1;
    // End of variables declaration//GEN-END:variables
}
