/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazSistema;

import Codigo.LogicaDeposito_Y_Retiro;
import java.awt.Color;

/**
 *
 * @author axels
 */
public class RealizarDeposito extends javax.swing.JFrame {

    /**
     * Creates new form RealizarDeposito
     */
    public RealizarDeposito() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.advertenciaCampoD1.setVisible(false);
        this.advertenciaCampoD2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanelRealizarDeposito = new javax.swing.JPanel();
        tituloDeposito = new javax.swing.JLabel();
        botonRealizarDeposito = new javax.swing.JPanel();
        tituloBotonRealizarDeposito = new javax.swing.JLabel();
        tituloMontoDeposito = new javax.swing.JLabel();
        ingresoMontoDeposito = new javax.swing.JTextField();
        tituloNoCuentaDeposito = new javax.swing.JLabel();
        ingresoNoCuentaDeposito = new javax.swing.JTextField();
        botonRegresoInicio1 = new javax.swing.JPanel();
        tituloRegresoInicio1 = new javax.swing.JLabel();
        advertenciaCampoD2 = new javax.swing.JLabel();
        advertenciaCampoD1 = new javax.swing.JLabel();
        avisoTransferencia = new javax.swing.JLabel();
        advertenciaExistenciaCuentaD = new javax.swing.JLabel();
        cuadroRealizarDeposito = new javax.swing.JLabel();
        fondoRealizarDeposito = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fondoPanelRealizarDeposito.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloDeposito.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        tituloDeposito.setForeground(new java.awt.Color(0, 0, 0));
        tituloDeposito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloDeposito.setText("Depósito");
        fondoPanelRealizarDeposito.add(tituloDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 50));

        botonRealizarDeposito.setBackground(new java.awt.Color(204, 204, 204));
        botonRealizarDeposito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRealizarDeposito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRealizarDepositoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRealizarDepositoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRealizarDepositoMouseExited(evt);
            }
        });

        tituloBotonRealizarDeposito.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tituloBotonRealizarDeposito.setForeground(new java.awt.Color(0, 0, 0));
        tituloBotonRealizarDeposito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloBotonRealizarDeposito.setText("Depositar");

        javax.swing.GroupLayout botonRealizarDepositoLayout = new javax.swing.GroupLayout(botonRealizarDeposito);
        botonRealizarDeposito.setLayout(botonRealizarDepositoLayout);
        botonRealizarDepositoLayout.setHorizontalGroup(
            botonRealizarDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonRealizarDepositoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tituloBotonRealizarDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        botonRealizarDepositoLayout.setVerticalGroup(
            botonRealizarDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonRealizarDepositoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tituloBotonRealizarDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fondoPanelRealizarDeposito.add(botonRealizarDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 150, 40));

        tituloMontoDeposito.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloMontoDeposito.setForeground(new java.awt.Color(51, 51, 51));
        tituloMontoDeposito.setText("Monto");
        fondoPanelRealizarDeposito.add(tituloMontoDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, -1));

        ingresoMontoDeposito.setBackground(new java.awt.Color(255, 255, 255));
        ingresoMontoDeposito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ingresoMontoDeposito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ingresoMontoDepositoFocusLost(evt);
            }
        });
        ingresoMontoDeposito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresoMontoDepositoKeyTyped(evt);
            }
        });
        fondoPanelRealizarDeposito.add(ingresoMontoDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 340, 40));

        tituloNoCuentaDeposito.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloNoCuentaDeposito.setForeground(new java.awt.Color(51, 51, 51));
        tituloNoCuentaDeposito.setText("No. Cuenta");
        fondoPanelRealizarDeposito.add(tituloNoCuentaDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, -1));

        ingresoNoCuentaDeposito.setBackground(new java.awt.Color(255, 255, 255));
        ingresoNoCuentaDeposito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ingresoNoCuentaDeposito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ingresoNoCuentaDepositoFocusLost(evt);
            }
        });
        ingresoNoCuentaDeposito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresoNoCuentaDepositoKeyTyped(evt);
            }
        });
        fondoPanelRealizarDeposito.add(ingresoNoCuentaDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 340, 40));

        botonRegresoInicio1.setBackground(new java.awt.Color(246, 245, 242));
        botonRegresoInicio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresoInicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegresoInicio1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegresoInicio1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegresoInicio1MouseExited(evt);
            }
        });

        tituloRegresoInicio1.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloRegresoInicio1.setForeground(new java.awt.Color(102, 102, 102));
        tituloRegresoInicio1.setText(" Regresar al Inicio");

        javax.swing.GroupLayout botonRegresoInicio1Layout = new javax.swing.GroupLayout(botonRegresoInicio1);
        botonRegresoInicio1.setLayout(botonRegresoInicio1Layout);
        botonRegresoInicio1Layout.setHorizontalGroup(
            botonRegresoInicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloRegresoInicio1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        botonRegresoInicio1Layout.setVerticalGroup(
            botonRegresoInicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloRegresoInicio1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        fondoPanelRealizarDeposito.add(botonRegresoInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 360, 50));

        advertenciaCampoD2.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        advertenciaCampoD2.setForeground(new java.awt.Color(153, 0, 0));
        advertenciaCampoD2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        advertenciaCampoD2.setText("CAMPO REQUERIDO");
        fondoPanelRealizarDeposito.add(advertenciaCampoD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 120, -1));

        advertenciaCampoD1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        advertenciaCampoD1.setForeground(new java.awt.Color(153, 0, 0));
        advertenciaCampoD1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        advertenciaCampoD1.setText("CAMPO REQUERIDO");
        fondoPanelRealizarDeposito.add(advertenciaCampoD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 120, -1));

        avisoTransferencia.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        avisoTransferencia.setForeground(new java.awt.Color(0, 153, 51));
        avisoTransferencia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fondoPanelRealizarDeposito.add(avisoTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 330, 15));

        advertenciaExistenciaCuentaD.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        advertenciaExistenciaCuentaD.setForeground(new java.awt.Color(153, 0, 0));
        advertenciaExistenciaCuentaD.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fondoPanelRealizarDeposito.add(advertenciaExistenciaCuentaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 330, 15));

        cuadroRealizarDeposito.setBackground(new java.awt.Color(246, 245, 242));
        cuadroRealizarDeposito.setOpaque(true);
        fondoPanelRealizarDeposito.add(cuadroRealizarDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 720));

        fondoRealizarDeposito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondos/fondos/fondoRealizarDeposito.png"))); // NOI18N
        fondoPanelRealizarDeposito.add(fondoRealizarDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanelRealizarDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanelRealizarDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresoInicio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresoInicio1MouseClicked
        Inicio regresarInicio1 = new Inicio();
        regresarInicio1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegresoInicio1MouseClicked

    private void botonRegresoInicio1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresoInicio1MouseEntered
        botonRegresoInicio1.setBackground(new Color(227,226,223));
    }//GEN-LAST:event_botonRegresoInicio1MouseEntered

    private void botonRegresoInicio1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresoInicio1MouseExited
        botonRegresoInicio1.setBackground(new Color(246,245,242));
    }//GEN-LAST:event_botonRegresoInicio1MouseExited

    private void botonRealizarDepositoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRealizarDepositoMouseEntered
        botonRealizarDeposito.setBackground(new Color(188,188,188));
    }//GEN-LAST:event_botonRealizarDepositoMouseEntered

    private void botonRealizarDepositoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRealizarDepositoMouseExited
        botonRealizarDeposito.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_botonRealizarDepositoMouseExited

    private void botonRealizarDepositoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRealizarDepositoMouseClicked
        this.avisoTransferencia.setText("");
//        this.advertenciaCampoD1.setVisible(false);
//        this.advertenciaCampoD2.setVisible(false);
        if(ingresoNoCuentaDeposito.getText().trim().isEmpty() || ingresoMontoDeposito.getText().trim().isEmpty()){
            if(ingresoNoCuentaDeposito.getText().trim().isEmpty()){
                advertenciaCampoD1.setVisible(true);
            }else{
                advertenciaCampoD1.setVisible(false);
            }
            if(ingresoMontoDeposito.getText().trim().isEmpty()){
                advertenciaCampoD2.setVisible(true);
            }else{
                advertenciaCampoD2.setVisible(false);
            }
        }else{
            String noCuenta = ingresoNoCuentaDeposito.getText();
            double monto = Double.parseDouble(ingresoMontoDeposito.getText());

            LogicaDeposito_Y_Retiro deposito = new LogicaDeposito_Y_Retiro(noCuenta, monto);

            deposito.leerDatosCuenta();
            deposito.deposito();
            this.advertenciaExistenciaCuentaD.setText(deposito.getAvisoCuenta());
            this.avisoTransferencia.setText(deposito.getAvisoTransaccion());
            this.ingresoNoCuentaDeposito.setText("");
            this.ingresoMontoDeposito.setText("");
            this.advertenciaCampoD1.setVisible(false);
            this.advertenciaCampoD2.setVisible(false);
        }
    }//GEN-LAST:event_botonRealizarDepositoMouseClicked

    private void ingresoMontoDepositoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresoMontoDepositoKeyTyped
        int key = evt.getKeyChar();
        
        boolean numero = key >= 48 && key <= 57 || key == 46;
        
        if(!numero){
            evt.consume();
        }
    }//GEN-LAST:event_ingresoMontoDepositoKeyTyped

    private void ingresoNoCuentaDepositoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresoNoCuentaDepositoKeyTyped
        int key = evt.getKeyChar();
        
        boolean numero = key >= 48 && key <= 57;
        
        if(!numero){
            evt.consume();
        }
    }//GEN-LAST:event_ingresoNoCuentaDepositoKeyTyped

    private void ingresoNoCuentaDepositoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoNoCuentaDepositoFocusLost
        if(ingresoNoCuentaDeposito.getText().trim().isEmpty()){
            advertenciaCampoD1.setVisible(true);
        }else{
            advertenciaCampoD1.setVisible(false);
        }
    }//GEN-LAST:event_ingresoNoCuentaDepositoFocusLost

    private void ingresoMontoDepositoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoMontoDepositoFocusLost
        if(ingresoMontoDeposito.getText().trim().isEmpty()){
            advertenciaCampoD2.setVisible(true);
        }else{
            advertenciaCampoD2.setVisible(false);
        }
    }//GEN-LAST:event_ingresoMontoDepositoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealizarDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealizarDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealizarDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealizarDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealizarDeposito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advertenciaCampoD1;
    private javax.swing.JLabel advertenciaCampoD2;
    private javax.swing.JLabel advertenciaExistenciaCuentaD;
    private javax.swing.JLabel avisoTransferencia;
    private javax.swing.JPanel botonRealizarDeposito;
    private javax.swing.JPanel botonRegresoInicio1;
    private javax.swing.JLabel cuadroRealizarDeposito;
    private javax.swing.JPanel fondoPanelRealizarDeposito;
    private javax.swing.JLabel fondoRealizarDeposito;
    private javax.swing.JTextField ingresoMontoDeposito;
    private javax.swing.JTextField ingresoNoCuentaDeposito;
    private javax.swing.JLabel tituloBotonRealizarDeposito;
    private javax.swing.JLabel tituloDeposito;
    private javax.swing.JLabel tituloMontoDeposito;
    private javax.swing.JLabel tituloNoCuentaDeposito;
    private javax.swing.JLabel tituloRegresoInicio1;
    // End of variables declaration//GEN-END:variables
}
