/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazSistema;

import Codigo.LogicaRegistroCliente;
import java.awt.Color;

/**
 *
 * @author axels
 */
public class RegistroCliente extends javax.swing.JFrame {

    /**
     * Creates new form RegistroCliente
     */
    public RegistroCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        advertenciaCampoRC1.setVisible(false);
        advertenciaCampoRC2.setVisible(false);
        advertenciaCampoRC3.setVisible(false);
        advertenciaCampoRC4.setVisible(false);
        advertenciaCampoRC5.setVisible(false);
        advertenciaCampoRC6.setVisible(false);
        advertenciaCampoRC7.setVisible(false);
        advertenciaCampoRC8.setVisible(false);
        avisoAgregadoExito.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanelRegistroCliente = new javax.swing.JPanel();
        tituloRegistroCliente = new javax.swing.JLabel();
        advertenciaCampoRC1 = new javax.swing.JLabel();
        advertenciaCampoRC2 = new javax.swing.JLabel();
        advertenciaCampoRC3 = new javax.swing.JLabel();
        advertenciaCampoRC4 = new javax.swing.JLabel();
        advertenciaCampoRC5 = new javax.swing.JLabel();
        advertenciaCampoRC6 = new javax.swing.JLabel();
        advertenciaCampoRC7 = new javax.swing.JLabel();
        advertenciaCampoRC8 = new javax.swing.JLabel();
        tituloIngresosMensuales = new javax.swing.JLabel();
        ingresoIngresosMensuales = new javax.swing.JTextField();
        tituloOcupacion = new javax.swing.JLabel();
        ingresoOcupacion = new javax.swing.JTextField();
        tituloCorreo = new javax.swing.JLabel();
        ingresoCorreo = new javax.swing.JTextField();
        tituloTelefono = new javax.swing.JLabel();
        ingresoTelefono = new javax.swing.JTextField();
        tituloDireccion = new javax.swing.JLabel();
        ingresoDireccion = new javax.swing.JTextField();
        tituloApellidos = new javax.swing.JLabel();
        ingresoApellidos = new javax.swing.JTextField();
        tituloNombre = new javax.swing.JLabel();
        salidaPrueba = new javax.swing.JLabel();
        ingresoNombre = new javax.swing.JTextField();
        tituloDPI = new javax.swing.JLabel();
        avisoAgregadoExito = new javax.swing.JLabel();
        ingresoDPI = new javax.swing.JTextField();
        botonRegistrarCliente = new javax.swing.JPanel();
        tituloBotonRegistrarCliente = new javax.swing.JLabel();
        botonRegresoInicio1 = new javax.swing.JPanel();
        tituloRegresoInicio1 = new javax.swing.JLabel();
        cuadroRegistroCliente = new javax.swing.JLabel();
        fondoRegistroClientes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fondoPanelRegistroCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloRegistroCliente.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        tituloRegistroCliente.setForeground(new java.awt.Color(0, 0, 0));
        tituloRegistroCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloRegistroCliente.setText("Registro de Cliente");
        fondoPanelRegistroCliente.add(tituloRegistroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 50));

        advertenciaCampoRC1.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        advertenciaCampoRC1.setForeground(new java.awt.Color(153, 0, 0));
        advertenciaCampoRC1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        advertenciaCampoRC1.setText("CAMPO REQUERIDO");
        fondoPanelRegistroCliente.add(advertenciaCampoRC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 120, -1));

        advertenciaCampoRC2.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        advertenciaCampoRC2.setForeground(new java.awt.Color(153, 0, 0));
        advertenciaCampoRC2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        advertenciaCampoRC2.setText("CAMPO REQUERIDO");
        fondoPanelRegistroCliente.add(advertenciaCampoRC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 120, -1));

        advertenciaCampoRC3.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        advertenciaCampoRC3.setForeground(new java.awt.Color(153, 0, 0));
        advertenciaCampoRC3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        advertenciaCampoRC3.setText("CAMPO REQUERIDO");
        fondoPanelRegistroCliente.add(advertenciaCampoRC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 120, -1));

        advertenciaCampoRC4.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        advertenciaCampoRC4.setForeground(new java.awt.Color(153, 0, 0));
        advertenciaCampoRC4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        advertenciaCampoRC4.setText("CAMPO REQUERIDO");
        fondoPanelRegistroCliente.add(advertenciaCampoRC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 120, -1));

        advertenciaCampoRC5.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        advertenciaCampoRC5.setForeground(new java.awt.Color(153, 0, 0));
        advertenciaCampoRC5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        advertenciaCampoRC5.setText("CAMPO REQUERIDO");
        fondoPanelRegistroCliente.add(advertenciaCampoRC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 120, -1));

        advertenciaCampoRC6.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        advertenciaCampoRC6.setForeground(new java.awt.Color(153, 0, 0));
        advertenciaCampoRC6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        advertenciaCampoRC6.setText("CAMPO REQUERIDO");
        fondoPanelRegistroCliente.add(advertenciaCampoRC6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 120, -1));

        advertenciaCampoRC7.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        advertenciaCampoRC7.setForeground(new java.awt.Color(153, 0, 0));
        advertenciaCampoRC7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        advertenciaCampoRC7.setText("CAMPO REQUERIDO");
        fondoPanelRegistroCliente.add(advertenciaCampoRC7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 120, -1));

        advertenciaCampoRC8.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        advertenciaCampoRC8.setForeground(new java.awt.Color(153, 0, 0));
        advertenciaCampoRC8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        advertenciaCampoRC8.setText("CAMPO REQUERIDO");
        fondoPanelRegistroCliente.add(advertenciaCampoRC8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 120, -1));

        tituloIngresosMensuales.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloIngresosMensuales.setForeground(new java.awt.Color(51, 51, 51));
        tituloIngresosMensuales.setText("Ingresos Mensuales");
        fondoPanelRegistroCliente.add(tituloIngresosMensuales, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 180, -1));

        ingresoIngresosMensuales.setBackground(new java.awt.Color(255, 255, 255));
        ingresoIngresosMensuales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ingresoIngresosMensuales.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ingresoIngresosMensualesFocusLost(evt);
            }
        });
        ingresoIngresosMensuales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresoIngresosMensualesKeyTyped(evt);
            }
        });
        fondoPanelRegistroCliente.add(ingresoIngresosMensuales, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 340, 40));

        tituloOcupacion.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloOcupacion.setForeground(new java.awt.Color(51, 51, 51));
        tituloOcupacion.setText("Ocupación");
        fondoPanelRegistroCliente.add(tituloOcupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 150, -1));

        ingresoOcupacion.setBackground(new java.awt.Color(255, 255, 255));
        ingresoOcupacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ingresoOcupacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ingresoOcupacionFocusLost(evt);
            }
        });
        fondoPanelRegistroCliente.add(ingresoOcupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 340, 40));

        tituloCorreo.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloCorreo.setForeground(new java.awt.Color(51, 51, 51));
        tituloCorreo.setText("Correo");
        fondoPanelRegistroCliente.add(tituloCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 150, -1));

        ingresoCorreo.setBackground(new java.awt.Color(255, 255, 255));
        ingresoCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ingresoCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ingresoCorreoFocusLost(evt);
            }
        });
        fondoPanelRegistroCliente.add(ingresoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 340, 40));

        tituloTelefono.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloTelefono.setForeground(new java.awt.Color(51, 51, 51));
        tituloTelefono.setText("Teléfono");
        fondoPanelRegistroCliente.add(tituloTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 150, -1));

        ingresoTelefono.setBackground(new java.awt.Color(255, 255, 255));
        ingresoTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ingresoTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ingresoTelefonoFocusLost(evt);
            }
        });
        ingresoTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresoTelefonoKeyTyped(evt);
            }
        });
        fondoPanelRegistroCliente.add(ingresoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 340, 40));

        tituloDireccion.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloDireccion.setForeground(new java.awt.Color(51, 51, 51));
        tituloDireccion.setText("Dirección");
        fondoPanelRegistroCliente.add(tituloDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 150, -1));

        ingresoDireccion.setBackground(new java.awt.Color(255, 255, 255));
        ingresoDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ingresoDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ingresoDireccionFocusLost(evt);
            }
        });
        fondoPanelRegistroCliente.add(ingresoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 340, 40));

        tituloApellidos.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloApellidos.setForeground(new java.awt.Color(51, 51, 51));
        tituloApellidos.setText("Apellidos");
        fondoPanelRegistroCliente.add(tituloApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 150, -1));

        ingresoApellidos.setBackground(new java.awt.Color(255, 255, 255));
        ingresoApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ingresoApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ingresoApellidosFocusLost(evt);
            }
        });
        fondoPanelRegistroCliente.add(ingresoApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 340, 40));

        tituloNombre.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloNombre.setForeground(new java.awt.Color(51, 51, 51));
        tituloNombre.setText("Nombre");
        fondoPanelRegistroCliente.add(tituloNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, -1));

        salidaPrueba.setForeground(new java.awt.Color(0, 0, 0));
        salidaPrueba.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fondoPanelRegistroCliente.add(salidaPrueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 700, 30));

        ingresoNombre.setBackground(new java.awt.Color(255, 255, 255));
        ingresoNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ingresoNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ingresoNombreFocusLost(evt);
            }
        });
        fondoPanelRegistroCliente.add(ingresoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 340, 40));

        tituloDPI.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloDPI.setForeground(new java.awt.Color(51, 51, 51));
        tituloDPI.setText("DPI");
        fondoPanelRegistroCliente.add(tituloDPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, -1));

        avisoAgregadoExito.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        avisoAgregadoExito.setForeground(new java.awt.Color(0, 204, 0));
        avisoAgregadoExito.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        avisoAgregadoExito.setText("Cliente agregado con éxito");
        fondoPanelRegistroCliente.add(avisoAgregadoExito, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 260, -1));

        ingresoDPI.setBackground(new java.awt.Color(255, 255, 255));
        ingresoDPI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ingresoDPI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ingresoDPIFocusLost(evt);
            }
        });
        ingresoDPI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresoDPIKeyTyped(evt);
            }
        });
        fondoPanelRegistroCliente.add(ingresoDPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 340, 40));

        botonRegistrarCliente.setBackground(new java.awt.Color(204, 204, 204));
        botonRegistrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegistrarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegistrarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegistrarClienteMouseExited(evt);
            }
        });

        tituloBotonRegistrarCliente.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        tituloBotonRegistrarCliente.setForeground(new java.awt.Color(0, 0, 0));
        tituloBotonRegistrarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloBotonRegistrarCliente.setText("Registrar Cliente");

        javax.swing.GroupLayout botonRegistrarClienteLayout = new javax.swing.GroupLayout(botonRegistrarCliente);
        botonRegistrarCliente.setLayout(botonRegistrarClienteLayout);
        botonRegistrarClienteLayout.setHorizontalGroup(
            botonRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloBotonRegistrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        botonRegistrarClienteLayout.setVerticalGroup(
            botonRegistrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloBotonRegistrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        fondoPanelRegistroCliente.add(botonRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 150, 40));

        botonRegresoInicio1.setBackground(new java.awt.Color(246, 245, 242));
        botonRegresoInicio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresoInicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegresoInicio1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegresoInicio1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegresoInicio1MouseExited(evt);
            }
        });

        tituloRegresoInicio1.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloRegresoInicio1.setForeground(new java.awt.Color(102, 102, 102));
        tituloRegresoInicio1.setText(" Regresar al Inicio");

        javax.swing.GroupLayout botonRegresoInicio1Layout = new javax.swing.GroupLayout(botonRegresoInicio1);
        botonRegresoInicio1.setLayout(botonRegresoInicio1Layout);
        botonRegresoInicio1Layout.setHorizontalGroup(
            botonRegresoInicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloRegresoInicio1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        botonRegresoInicio1Layout.setVerticalGroup(
            botonRegresoInicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloRegresoInicio1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        fondoPanelRegistroCliente.add(botonRegresoInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 720, 50));

        cuadroRegistroCliente.setBackground(new java.awt.Color(246, 245, 242));
        cuadroRegistroCliente.setOpaque(true);
        fondoPanelRegistroCliente.add(cuadroRegistroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 720));

        fondoRegistroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondos/fondos/fondoRegistroCliente.png"))); // NOI18N
        fondoPanelRegistroCliente.add(fondoRegistroClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanelRegistroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanelRegistroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresoInicio1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresoInicio1MouseEntered
        botonRegresoInicio1.setBackground(new Color(227,226,223));
    }//GEN-LAST:event_botonRegresoInicio1MouseEntered

    private void botonRegresoInicio1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresoInicio1MouseExited
        botonRegresoInicio1.setBackground(new Color(246,245,242));
    }//GEN-LAST:event_botonRegresoInicio1MouseExited

    private void botonRegresoInicio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresoInicio1MouseClicked
        Inicio regresarInicio1 = new Inicio();
        regresarInicio1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegresoInicio1MouseClicked

    private void botonRegistrarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarClienteMouseEntered
        botonRegistrarCliente.setBackground(new Color(188,188,188));
    }//GEN-LAST:event_botonRegistrarClienteMouseEntered

    private void botonRegistrarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarClienteMouseExited
        botonRegistrarCliente.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_botonRegistrarClienteMouseExited

    private void ingresoDPIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresoDPIKeyTyped
        int key = evt.getKeyChar();
        
        boolean numero = key >= 48 && key <= 57;
        
        if(!numero){
            evt.consume();
        }
        
        if(ingresoDPI.getText().length() >= 13){
            evt.consume();
        }
    }//GEN-LAST:event_ingresoDPIKeyTyped

    private void ingresoTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresoTelefonoKeyTyped
        int key = evt.getKeyChar();
        
        boolean numero = key >= 48 && key <= 57 || key == 32 || key == 43;
        
        if(!numero){
            evt.consume();
        }
        
        if(ingresoTelefono.getText().length() >= 13){
            evt.consume();
        }
    }//GEN-LAST:event_ingresoTelefonoKeyTyped

    private void ingresoIngresosMensualesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresoIngresosMensualesKeyTyped
        int key = evt.getKeyChar();
        
        boolean numero = key >= 48 && key <= 57 || key == 46;
        
        if(!numero){
            evt.consume();
        }
    }//GEN-LAST:event_ingresoIngresosMensualesKeyTyped

    private void ingresoDPIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoDPIFocusLost
        if(ingresoDPI.getText().trim().isEmpty()){
            advertenciaCampoRC1.setVisible(true);
        }else{
            advertenciaCampoRC1.setVisible(false);
        }
    }//GEN-LAST:event_ingresoDPIFocusLost

    private void ingresoTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoTelefonoFocusLost
        if(ingresoTelefono.getText().trim().isEmpty()){
            advertenciaCampoRC2.setVisible(true);
        }else{
            advertenciaCampoRC2.setVisible(false);
        }
    }//GEN-LAST:event_ingresoTelefonoFocusLost

    private void ingresoNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoNombreFocusLost
        if(ingresoNombre.getText().trim().isEmpty()){
            advertenciaCampoRC3.setVisible(true);
        }else{
            advertenciaCampoRC3.setVisible(false);
        }
    }//GEN-LAST:event_ingresoNombreFocusLost

    private void ingresoCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoCorreoFocusLost
        if(ingresoCorreo.getText().trim().isEmpty()){
            advertenciaCampoRC4.setVisible(true);
        }else{
            advertenciaCampoRC4.setVisible(false);
        }
    }//GEN-LAST:event_ingresoCorreoFocusLost

    private void ingresoApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoApellidosFocusLost
        if(ingresoApellidos.getText().trim().isEmpty()){
            advertenciaCampoRC5.setVisible(true);
        }else{
            advertenciaCampoRC5.setVisible(false);
        }
    }//GEN-LAST:event_ingresoApellidosFocusLost

    private void ingresoOcupacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoOcupacionFocusLost
        if(ingresoOcupacion.getText().trim().isEmpty()){
            advertenciaCampoRC6.setVisible(true);
        }else{
            advertenciaCampoRC6.setVisible(false);
        }
    }//GEN-LAST:event_ingresoOcupacionFocusLost

    private void ingresoDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoDireccionFocusLost
        if(ingresoDireccion.getText().trim().isEmpty()){
            advertenciaCampoRC7.setVisible(true);
        }else{
            advertenciaCampoRC7.setVisible(false);
        }
    }//GEN-LAST:event_ingresoDireccionFocusLost

    private void ingresoIngresosMensualesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ingresoIngresosMensualesFocusLost
        if(ingresoIngresosMensuales.getText().trim().isEmpty()){
            advertenciaCampoRC8.setVisible(true);
        }else{
            advertenciaCampoRC8.setVisible(false);
        }
    }//GEN-LAST:event_ingresoIngresosMensualesFocusLost

    private void botonRegistrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarClienteMouseClicked
        avisoAgregadoExito.setVisible(false);
        if(ingresoDPI.getText().trim().isEmpty() || ingresoTelefono.getText().trim().isEmpty() ||
           ingresoNombre.getText().trim().isEmpty() || ingresoCorreo.getText().trim().isEmpty() ||
           ingresoApellidos.getText().trim().isEmpty() || ingresoOcupacion.getText().trim().isEmpty() ||
           ingresoDireccion.getText().trim().isEmpty() || ingresoIngresosMensuales.getText().trim().isEmpty()){
            if(ingresoDPI.getText().trim().isEmpty()){
                advertenciaCampoRC1.setVisible(true);
            }else{
                advertenciaCampoRC1.setVisible(false);
            }
            if(ingresoTelefono.getText().trim().isEmpty()){
                advertenciaCampoRC2.setVisible(true);
            }else{
                advertenciaCampoRC2.setVisible(false);
            }
            if(ingresoNombre.getText().trim().isEmpty()){
                advertenciaCampoRC3.setVisible(true);
            }else{
                advertenciaCampoRC3.setVisible(false);
            }
            if(ingresoCorreo.getText().trim().isEmpty()){
                advertenciaCampoRC4.setVisible(true);
            }else{
                advertenciaCampoRC4.setVisible(false);
            }
            if(ingresoApellidos.getText().trim().isEmpty()){
                advertenciaCampoRC5.setVisible(true);
            }else{
                advertenciaCampoRC5.setVisible(false);
            }
            if(ingresoOcupacion.getText().trim().isEmpty()){
                advertenciaCampoRC6.setVisible(true);
            }else{
                advertenciaCampoRC6.setVisible(false);
            }
            if(ingresoDireccion.getText().trim().isEmpty()){
                advertenciaCampoRC7.setVisible(true);
            }else{
                advertenciaCampoRC7.setVisible(false);
            }
            if(ingresoIngresosMensuales.getText().trim().isEmpty()){
                advertenciaCampoRC8.setVisible(true);
            }else{
                advertenciaCampoRC8.setVisible(false);
            }
        }else{
            String dpi = ingresoDPI.getText();
            String nombre = ingresoNombre.getText();
            String apellido = ingresoApellidos.getText();
            String direccion = ingresoDireccion.getText();
            String telefono = ingresoTelefono.getText();
            String correo = ingresoCorreo.getText();
            String ocupacion = ingresoOcupacion.getText();
            Float ingresomensual = Float.parseFloat(ingresoIngresosMensuales.getText());
            
            LogicaRegistroCliente registrarCliente = new LogicaRegistroCliente(dpi, nombre, apellido, direccion, telefono, correo, ocupacion, ingresomensual);
            registrarCliente.realizarRegistroUsuario();
            
            avisoAgregadoExito.setVisible(true);
            
            ingresoDPI.setText("");
            ingresoNombre.setText("");
            ingresoApellidos.setText("");
            ingresoDireccion.setText("");
            ingresoTelefono.setText("");
            ingresoCorreo.setText("");
            ingresoOcupacion.setText("");
            ingresoIngresosMensuales.setText("");
        }
    }//GEN-LAST:event_botonRegistrarClienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advertenciaCampoRC1;
    private javax.swing.JLabel advertenciaCampoRC2;
    private javax.swing.JLabel advertenciaCampoRC3;
    private javax.swing.JLabel advertenciaCampoRC4;
    private javax.swing.JLabel advertenciaCampoRC5;
    private javax.swing.JLabel advertenciaCampoRC6;
    private javax.swing.JLabel advertenciaCampoRC7;
    private javax.swing.JLabel advertenciaCampoRC8;
    private javax.swing.JLabel avisoAgregadoExito;
    private javax.swing.JPanel botonRegistrarCliente;
    private javax.swing.JPanel botonRegresoInicio1;
    private javax.swing.JLabel cuadroRegistroCliente;
    private javax.swing.JPanel fondoPanelRegistroCliente;
    private javax.swing.JLabel fondoRegistroClientes;
    private javax.swing.JTextField ingresoApellidos;
    private javax.swing.JTextField ingresoCorreo;
    private javax.swing.JTextField ingresoDPI;
    private javax.swing.JTextField ingresoDireccion;
    private javax.swing.JTextField ingresoIngresosMensuales;
    private javax.swing.JTextField ingresoNombre;
    private javax.swing.JTextField ingresoOcupacion;
    private javax.swing.JTextField ingresoTelefono;
    private javax.swing.JLabel salidaPrueba;
    private javax.swing.JLabel tituloApellidos;
    private javax.swing.JLabel tituloBotonRegistrarCliente;
    private javax.swing.JLabel tituloCorreo;
    private javax.swing.JLabel tituloDPI;
    private javax.swing.JLabel tituloDireccion;
    private javax.swing.JLabel tituloIngresosMensuales;
    private javax.swing.JLabel tituloNombre;
    private javax.swing.JLabel tituloOcupacion;
    private javax.swing.JLabel tituloRegistroCliente;
    private javax.swing.JLabel tituloRegresoInicio1;
    private javax.swing.JLabel tituloTelefono;
    // End of variables declaration//GEN-END:variables
}
