/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazSistema;

import Codigo.LogicaReportesExcel;
import Codigo.LogicaReportesTXT;
import java.awt.Color;

/**
 *
 * @author axels
 */
public class Reporte extends javax.swing.JFrame {

    /**
     * Creates new form Reporte
     */
    public Reporte() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanelReportes = new javax.swing.JPanel();
        tituloReportes = new javax.swing.JLabel();
        botonEstadoCuenta = new javax.swing.JPanel();
        tituloBotonEstadoCuenta = new javax.swing.JLabel();
        botonOperacionesDia = new javax.swing.JPanel();
        tituloBotonOperacionesDia = new javax.swing.JLabel();
        botonSaldoCuentas = new javax.swing.JPanel();
        tituloBotonSaldoCuentas = new javax.swing.JLabel();
        botonRegresoInicio1 = new javax.swing.JPanel();
        tituloRegresoInicio1 = new javax.swing.JLabel();
        avisoReporteOperacionesDia = new javax.swing.JLabel();
        avisoReporteExcel = new javax.swing.JLabel();
        cuadroReportes = new javax.swing.JLabel();
        fondoReportes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fondoPanelReportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloReportes.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        tituloReportes.setForeground(new java.awt.Color(0, 0, 0));
        tituloReportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloReportes.setText("Reportes");
        fondoPanelReportes.add(tituloReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 50));

        botonEstadoCuenta.setBackground(new java.awt.Color(246, 245, 242));
        botonEstadoCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEstadoCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEstadoCuentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonEstadoCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEstadoCuentaMouseExited(evt);
            }
        });

        tituloBotonEstadoCuenta.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        tituloBotonEstadoCuenta.setForeground(new java.awt.Color(51, 51, 51));
        tituloBotonEstadoCuenta.setText(" Estado de Cuenta");

        javax.swing.GroupLayout botonEstadoCuentaLayout = new javax.swing.GroupLayout(botonEstadoCuenta);
        botonEstadoCuenta.setLayout(botonEstadoCuentaLayout);
        botonEstadoCuentaLayout.setHorizontalGroup(
            botonEstadoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloBotonEstadoCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        botonEstadoCuentaLayout.setVerticalGroup(
            botonEstadoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloBotonEstadoCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        fondoPanelReportes.add(botonEstadoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 360, 50));

        botonOperacionesDia.setBackground(new java.awt.Color(246, 245, 242));
        botonOperacionesDia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonOperacionesDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonOperacionesDiaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonOperacionesDiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonOperacionesDiaMouseExited(evt);
            }
        });

        tituloBotonOperacionesDia.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        tituloBotonOperacionesDia.setForeground(new java.awt.Color(51, 51, 51));
        tituloBotonOperacionesDia.setText(" Operaciones del día");

        javax.swing.GroupLayout botonOperacionesDiaLayout = new javax.swing.GroupLayout(botonOperacionesDia);
        botonOperacionesDia.setLayout(botonOperacionesDiaLayout);
        botonOperacionesDiaLayout.setHorizontalGroup(
            botonOperacionesDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloBotonOperacionesDia, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        botonOperacionesDiaLayout.setVerticalGroup(
            botonOperacionesDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloBotonOperacionesDia, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        fondoPanelReportes.add(botonOperacionesDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 360, 50));

        botonSaldoCuentas.setBackground(new java.awt.Color(246, 245, 242));
        botonSaldoCuentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSaldoCuentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSaldoCuentasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSaldoCuentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonSaldoCuentasMouseExited(evt);
            }
        });

        tituloBotonSaldoCuentas.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        tituloBotonSaldoCuentas.setForeground(new java.awt.Color(51, 51, 51));
        tituloBotonSaldoCuentas.setText(" Saldo de Todas las Cuentas");

        javax.swing.GroupLayout botonSaldoCuentasLayout = new javax.swing.GroupLayout(botonSaldoCuentas);
        botonSaldoCuentas.setLayout(botonSaldoCuentasLayout);
        botonSaldoCuentasLayout.setHorizontalGroup(
            botonSaldoCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloBotonSaldoCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        botonSaldoCuentasLayout.setVerticalGroup(
            botonSaldoCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloBotonSaldoCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        fondoPanelReportes.add(botonSaldoCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 360, 50));

        botonRegresoInicio1.setBackground(new java.awt.Color(246, 245, 242));
        botonRegresoInicio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegresoInicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonRegresoInicio1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegresoInicio1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegresoInicio1MouseExited(evt);
            }
        });

        tituloRegresoInicio1.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        tituloRegresoInicio1.setForeground(new java.awt.Color(102, 102, 102));
        tituloRegresoInicio1.setText(" Regresar al Inicio");

        javax.swing.GroupLayout botonRegresoInicio1Layout = new javax.swing.GroupLayout(botonRegresoInicio1);
        botonRegresoInicio1.setLayout(botonRegresoInicio1Layout);
        botonRegresoInicio1Layout.setHorizontalGroup(
            botonRegresoInicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloRegresoInicio1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        botonRegresoInicio1Layout.setVerticalGroup(
            botonRegresoInicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloRegresoInicio1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        fondoPanelReportes.add(botonRegresoInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 360, 50));

        avisoReporteOperacionesDia.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        avisoReporteOperacionesDia.setForeground(new java.awt.Color(0, 153, 0));
        avisoReporteOperacionesDia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fondoPanelReportes.add(avisoReporteOperacionesDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 340, 15));

        avisoReporteExcel.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        avisoReporteExcel.setForeground(new java.awt.Color(0, 153, 0));
        avisoReporteExcel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fondoPanelReportes.add(avisoReporteExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 430, 340, 15));

        cuadroReportes.setBackground(new java.awt.Color(246, 245, 242));
        cuadroReportes.setOpaque(true);
        fondoPanelReportes.add(cuadroReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 720));

        fondoReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondos/fondos/fondoReportes.png"))); // NOI18N
        fondoPanelReportes.add(fondoReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanelReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanelReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEstadoCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEstadoCuentaMouseEntered
        botonEstadoCuenta.setBackground(new Color(227,226,223));
    }//GEN-LAST:event_botonEstadoCuentaMouseEntered

    private void botonEstadoCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEstadoCuentaMouseExited
        botonEstadoCuenta.setBackground(new Color(246,245,242));
    }//GEN-LAST:event_botonEstadoCuentaMouseExited

    private void botonOperacionesDiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonOperacionesDiaMouseEntered
        botonOperacionesDia.setBackground(new Color(227,226,223));
    }//GEN-LAST:event_botonOperacionesDiaMouseEntered

    private void botonOperacionesDiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonOperacionesDiaMouseExited
        botonOperacionesDia.setBackground(new Color(246,245,242));
    }//GEN-LAST:event_botonOperacionesDiaMouseExited

    private void botonSaldoCuentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSaldoCuentasMouseEntered
        botonSaldoCuentas.setBackground(new Color(227,226,223));
    }//GEN-LAST:event_botonSaldoCuentasMouseEntered

    private void botonSaldoCuentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSaldoCuentasMouseExited
        botonSaldoCuentas.setBackground(new Color(246,245,242));
    }//GEN-LAST:event_botonSaldoCuentasMouseExited

    private void botonRegresoInicio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresoInicio1MouseClicked
        Inicio regresarInicio1 = new Inicio();
        regresarInicio1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonRegresoInicio1MouseClicked

    private void botonRegresoInicio1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresoInicio1MouseEntered
        botonRegresoInicio1.setBackground(new Color(227,226,223));
    }//GEN-LAST:event_botonRegresoInicio1MouseEntered

    private void botonRegresoInicio1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegresoInicio1MouseExited
        botonRegresoInicio1.setBackground(new Color(246,245,242));
    }//GEN-LAST:event_botonRegresoInicio1MouseExited

    private void botonEstadoCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEstadoCuentaMouseClicked
        EstadoCuenta abrirEstadoCuenta = new EstadoCuenta();
        abrirEstadoCuenta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonEstadoCuentaMouseClicked

    private void botonSaldoCuentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSaldoCuentasMouseClicked
        LogicaReportesExcel realizarReporteExel = new LogicaReportesExcel();
        realizarReporteExel.generarReporteExcel();
        this.avisoReporteExcel.setText(realizarReporteExel.getAvisoArchivoCreado());
    }//GEN-LAST:event_botonSaldoCuentasMouseClicked

    private void botonOperacionesDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonOperacionesDiaMouseClicked
        LogicaReportesTXT reportesDia = new LogicaReportesTXT();
        reportesDia.realizarReporteOperacionesDia();
        this.avisoReporteOperacionesDia.setText(reportesDia.getAvisoArchivoCreado());
    }//GEN-LAST:event_botonOperacionesDiaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoReporteExcel;
    private javax.swing.JLabel avisoReporteOperacionesDia;
    private javax.swing.JPanel botonEstadoCuenta;
    private javax.swing.JPanel botonOperacionesDia;
    private javax.swing.JPanel botonRegresoInicio1;
    private javax.swing.JPanel botonSaldoCuentas;
    private javax.swing.JLabel cuadroReportes;
    private javax.swing.JPanel fondoPanelReportes;
    private javax.swing.JLabel fondoReportes;
    private javax.swing.JLabel tituloBotonEstadoCuenta;
    private javax.swing.JLabel tituloBotonOperacionesDia;
    private javax.swing.JLabel tituloBotonSaldoCuentas;
    private javax.swing.JLabel tituloRegresoInicio1;
    private javax.swing.JLabel tituloReportes;
    // End of variables declaration//GEN-END:variables
}
